### ISSUE TITLE
No UI showing the character cash, bank balance or dirty money.

### ISSUE THREAD

**Issue by SirMagicTurtle** [2nd-alarm/FiveM#101]
**Describe the bug**
The UI that would usually display the character cash, bank balance or dirty money is not showing.

**To Reproduce**
1. relog

**Expected behavior**
The UI can be found in the top right hand corner.

**Screenshots**
![image](https://user-images.githubusercontent.com/83597225/140648009-e94e4137-d4c2-41ee-bed0-549cbf974ca7.png)
![image](https://user-images.githubusercontent.com/83597225/140648018-86adc5a0-7ea0-42d7-8528-6755b71ed895.png)

**Comment by Jamie-D-T** [comment]
Client not loading properly
