### ISSUE TITLE
[BUG] Slash command suggestions stuck on screen

### ISSUE THREAD

**Issue by PoliceTrooper** [2nd-alarm/FiveM#103]
**Describe the bug**
Pressing escape or cycling letters while the autocomplete options for slash commands appear (after typing / in chat) will make them stuck on top of the screen until a relog.

**To Reproduce**
Steps to reproduce the behavior with escape menu:
1. Open the chat
2. Type / followed by a few letters
3. Press the escape button
4. The suggestions will be stuck on screen

Steps to reproduce the behavior without escape menu:
1. Open the chat
2. Type / followed by a few letters
3. Cycle the letters leaving the slash there
4. After some letters the suggestions will be stuck on screen

**Expected behavior**
The recommendations should disappear when the chat is closed.

**Screenshots**
![image](https://user-images.githubusercontent.com/83592968/141211285-f6016f0d-a5d3-472e-b2ac-6dc1af066ebf.png)

**Comment by Gavin72** [comment]
This bug still seems to be in the game.

**Comment by Jamie-D-T** [comment]
Fixed it minor issue with syntax
