### ISSUE TITLE
Picklocks not always being removed from the inventory when used/broken

### ISSUE THREAD

**Issue by SirMagicTurtle** [2nd-alarm/FiveM#104]
![image](https://user-images.githubusercontent.com/83597225/141338022-e1a191c2-97ec-41da-a02b-373d9b058947.png)
![image](https://user-images.githubusercontent.com/83597225/141338028-bb3d317a-d639-485b-993f-7617a2988a23.png)
![image](https://user-images.githubusercontent.com/83597225/141338026-37afb5d9-aea0-447a-9c6e-489aa8708738.png)
**Describe the bug**
When using a pick lock and it being broken it sometimes still allows you to use use it. I have 3 picklocks all spread out, I used one (the pick in slot one of the inventory). The inventory shows that there is one pick  and when I use and then break the pick it is still able to be used again.

**To Reproduce**
1. Buy more then one picklock
2. Take note of how many picklocks you have (best to spread them out to 1 picklot in each slop and not to stack them to make it easier to see).
3. Break one pick lock by using it, and check your inventory to see how many it says you have (Use TAB as the Z inventory dosnt update after using one)
4. You should still see the pick and be able to use it in some cases.

**Expected behavior**
The pick lock is removed if broken.

**Screenshots**
![image](https://user-images.githubusercontent.com/83597225/141338835-ed03fbc8-c4f7-4b20-bfd0-3a63059d711a.png)

**Additional context**

**Comment by SirMagicTurtle** [comment]
Apologies, some screenshots where put in the wrong place but they still show how after using a picklock it is in my inventory and can be used again.

**Comment by Jamie-D-T** [comment]
This is solved this was based on random chance now it is always going to remove the lockpicks on completion
