### ISSUE TITLE
[BUG] /depot does not always work. It says it was brought to the depot but the vehicle remains and is still functional. 

### ISSUE THREAD

**Issue by Special-G** [2nd-alarm/FiveM#112]
**Describe the bug**

**To Reproduce**
1. Grab a car and try to /depot it. sometimes it works, other times it does not.

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**

**Comment by Jamie-D-T** [comment]
Vehicle is not a registered vehicle you need to sit in it for like up to 1 min for it to release this is a vehicle that a player is using

**Comment by Mumbleb** [comment]
Issue Resolved.
