### ISSUE TITLE
Somtimes when you buy a car from the dealer they spawn in on the roof

### ISSUE THREAD

**Issue by Gavin72** [2nd-alarm/FiveM#117]
![FiveM -  2nd Alarm Roleplay Community  Development 2 0  12_15_2021 9_41_36 PM](https://user-images.githubusercontent.com/85081772/146298352-e9bb11bd-5a83-4dab-b37e-f22b74c3b966.png)

**Comment by Mumbleb** [comment]
Spawn Point Moved
