### ISSUE TITLE
Being stuck in the Benny's menu

### ISSUE THREAD

**Issue by SirMagicTurtle** [2nd-alarm/FiveM#119]
When entering Benny's vehicle workshop there I have encountered a even twice in where the menu is stuck and I am unable to enter the workshop or exit the menu.

  Go to Benny's auto shop at 9038
  Enter and exit the menu until the bug occurs
  
  The menu would disappear and allow you to exit the shop when you use the esc key
  
  
![image](https://user-images.githubusercontent.com/83597225/146618969-7dd5087f-6d15-485b-8db9-f92651543f4b.png)
![image](https://user-images.githubusercontent.com/83597225/146618985-e616e690-b0d1-4eb9-a124-00fdeb2c3b53.png)

**Comment by Jamie-D-T** [comment]
This issue cannot be processed due to the fact you have not followed the template.
