### ISSUE TITLE
[BUG] The "Toggle Extras" button in Benny's doesn't work.

### ISSUE THREAD

**Issue by PoliceTrooper** [2nd-alarm/FiveM#121]
**Describe the bug**
The "Toggle Extras" button in Benny's doesn't work. Nothing happens to the extras when it is used.

**To Reproduce**
1. Go to Benny's
2. Click on Toggle Extras

**Expected behavior**
The extras modifications done in the F10 menu should apply

**Comment by Mumbleb** [comment]
Use F1/F10 Menu Instead.
