### ISSUE TITLE
Being able to leave prison

### ISSUE THREAD

**Issue by SirMagicTurtle** [2nd-alarm/FiveM#122]
**Describe the bug**
If you are imprisoned you can leave the game, relog and choose to spawn at a different location.

**To Reproduce**
1. Be placed in prison
2. Leave the game
3. Load the game back up as the same character and choose a different location.

**Expected behavior**
You would have the menu disabled or be given a error that results in the game not allowing you to spawn in outside of the prison.

**Screenshots**

**Additional context**

**Comment by Jamie-D-T** [comment]
This is not a bug this is the anticheat kicking in
