### ISSUE TITLE
Clearer way to leave the prison

### ISSUE THREAD

**Issue by SirMagicTurtle** [2nd-alarm/FiveM#123]
**Is your feature request related to a problem? Please describe.**
When in the prison there is no clear or obvious way of finding the reception in order to leave the prison. This leads to confusion and staying in the prison for longer then needed.

**Describe the solution you'd like**
A indicator such as a beacon or a path to only be visible whilst in the prison that shows the location of the reception.

**Describe alternatives you've considered**
Adding a system that automatically releases a prisoner or a notification that also aids in helping them leave.

**Additional context**

**Links**
Link anything that may help us

**Comment by Jamie-D-T** [comment]
These are already in the game and do happen.
