### ISSUE TITLE
[BUG] Barriers at Mission row PD not opening

### ISSUE THREAD

**Issue by Divison21** [2nd-alarm/FiveM#125]
**Describe the bug**
The barriers at te PD are not going down unless i tap them with my car as if the barriers are stuck, 

**To Reproduce**
1. Go to the entrance or exit, hit the unlock key and the barriers will be stuck up and will not go down unless an entity such as my person or a car bumps them

**Comment by Jamie-D-T** [comment]
That is your latency you just need to wait they update server aided first
