### ISSUE TITLE
[BUG] PD garage is not working

### ISSUE THREAD

**Issue by XSh4dowFaLLX** [2nd-alarm/FiveM#127]
**Describe the bug**
PD garage will not hold my vehicles. Try to look vehicles up on the phone and they've all disappeared.

**To Reproduce**
1. Go to PD garage
2. Click on My Vehicles
3. See error (at least for me)

**Expected behavior**
PD vehicles store like they have before

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**

**Comment by Jamie-D-T** [comment]
fixed
