### ISSUE TITLE
[BUG] Notification is spammed in jail

### ISSUE THREAD

**Issue by acco4321** [2nd-alarm/FiveM#130]
**Describe the bug**
When the "clunk" noise sounds, to lock you in jail, you get a spammed notification "Seems like it is jammed try again later..."

**To Reproduce**
1. Get jailed
2. Wait for the clunk noise
3. Observe the notification be spammed thousands of times very quickly

**Expected behavior**
The notification appears once

**Screenshots**
[Image](https://i.imgur.com/Rsz1B1N.png)

**Comment by Jamie-D-T** [comment]
Patched as of next restart
