### ISSUE TITLE
[BUG] Civilian CAD won't update info

### ISSUE THREAD

**Issue by XSh4dowFaLLX** [2nd-alarm/FiveM#131]
**Describe the bug**
When updating information in the civilian CAD, there is no option to select gender, which is a required field, and therefore you can't update the info.

**To Reproduce**
1. Go to the Civilian Dashboard
2. Click on your character
3. Select the Gender drop-down menu

**Expected behavior**
There should be two gender options in the menu.

**Screenshots**
Can DM a screenshot

**Additional context**

**Comment by Jamie-D-T** [comment]
We are aware of error we are fixing asap (next restart)

**Comment by Jamie-D-T** [comment]
Fixed
