### ISSUE TITLE
[BUG] My Handgun broke after three shots fired

### ISSUE THREAD

**Issue by TacoCat7745** [2nd-alarm/FiveM#133]
**Describe the bug**
I bought a brand new gun legally from ammunation, then when I shot it ONLY three times, It said it broke and it was unusable
 
**To Reproduce**
1. Go to Ammunation
2. Buy a weapon
3. Shoot it a couple of times
4. See if it breaks

**Expected behavior**
I expected the gun to work for a while before It breaking

**Screenshots**
![image](https://user-images.githubusercontent.com/71361069/151719668-dd0e3bad-1be4-44ad-b19e-73f4261e5d88.png)

**Additional context**
Gun was loaded

**Comment by Mumbleb** [comment]
Issue was tested by Development Team, No issues found.
