### ISSUE TITLE
[BUG] Police get stressed when exceeding 115 MPH even when a seatbelt is in use. 

### ISSUE THREAD

**Issue by Special-G** [2nd-alarm/FiveM#135]
**Describe the bug**

In a car like a charger which is a pursuit vehicle, we need to go over 100 mph from time to time. If you are driving a vehicle that can go above 110 mph and you are both on duty, and have a seatbelt on, you will get stress. 

**To Reproduce**
Get a pursuit vehicle and go above 110 mph for an amount of time. 

**Expected behavior**
You get stressed. 

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**

**Comment by Jamie-D-T** [comment]
You do get stressed and you expect to
Get stress there's no issue here then

**Comment by Jamie-D-T** [comment]
Not to mention the fact that it is meant to happen that way either way
