### ISSUE TITLE
[BUG] Civilians have access to PD and FD channels on the radio

### ISSUE THREAD

**Issue by Special-G** [2nd-alarm/FiveM#136]
**Describe the bug**
When playing civilian, you can access, listen to, and broadcast on the PD and FD radio band. 

**To Reproduce**
1. Make a Civ Character
2. Get a radio
3. Tune to PD and FD channels
4. Transmit if you would like.

**Expected behavior**
Channels should be blocked to anyone not playing PD/FD

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**

**Comment by Mumbleb** [comment]
issue resolved.
