### ISSUE TITLE
[BUG] Benefactor Glendale always gets stuck at Benny's

### ISSUE THREAD

**Issue by acco4321** [2nd-alarm/FiveM#137]
**Describe the bug**
Whenever you get into the benny's with the benefactor glendale, you are softlocked inside benny's without the menu.

**To Reproduce**
1. Go to Benny's in the Glendale
2. Enter it using E
3. Try to leave

**Expected behavior**
You see the menu

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**
Persisted after a server restart, multiple users, and a relog.

**Comment by Mumbleb** [comment]
Issue Resolved.

**Comment by acco4321** [comment]
Repro'd at Harmony Benny's off of 68, and the one downtown in the alley.
Will get a postal when I get home.
