### ISSUE TITLE
[BUG] <Police Camaro can't change livery with F10, can't change color on Benny's shop>

### ISSUE THREAD

**Issue by DidntRemember** [2nd-alarm/FiveM#138]
**Describe the bug**
Camaro appear with SATD livery, with F10 menu you can't change or remove it. 
Camaro appear with a stock Grey color, if you want to change it to Benny, even if you choose a different color, it doesn't change, remain grey. 

**To Reproduce**
1. 'buy a new camaro'
2. 'try to change livery with F10, or color on Benny's'
3.  'nothing change'
4. See error, remain Grey stock with SATD livery 

**Expected behavior**
I can change livery (like for other LSPD patrol car) or remove it (Undercover). Change color, to make it adeguate for service.

**Comment by Mumbleb** [comment]
Vehicle Colour can be changed using Pearlescent Colour in Bennys. and the Vehicle only has one Livery on it
