### ISSUE TITLE
[BUG] Infinite Boats

### ISSUE THREAD

**Issue by acco4321** [2nd-alarm/FiveM#139]
**Describe the bug**
Once you buy a boat, you can get infinite amounts of the boat

**To Reproduce**
1. Go to the boat shop, purchase any
2. Store it in the boathouse
3. Go to the depot and take it out
4. Park the boat and go back to the depot, you can get the boat again

**Expected behavior**
You can only get out your purchased boats in their respective quantities

**Screenshots**
https://i.imgur.com/PKW3XsN.jpeg

**Additional context**
Only tested with the dinghy

**Comment by Mumbleb** [comment]
Will be Fixed with QB Core Update
