### ISSUE TITLE
[BUG] Paleto Hospital not enterable

### ISSUE THREAD

**Issue by XSh4dowFaLLX** [2nd-alarm/FiveM#142]
**Describe the bug**
When attempting to enter the Paleto Bay Clinic the door opens but you cannot enter the building.

**To Reproduce**
1. Go to 1049
2. Go to the front door of the clinic
3. Try to walk in

**Expected behavior**
The Paleto Bay Clinic should work as intended and should be enterable.

**Screenshots**
https://imgur.com/i8f5YCW

**Additional context**
Hospital used to work before but for some reason it stopped working.

**Comment by Mumbleb** [comment]
temporary Teleporter placed to enter and exit. While we Investigate the broken collisions

**Comment by Jamie-D-T** [comment]
This asset has been demolished.
