### ISSUE TITLE
[BUG] Duplicating stretcher

### ISSUE THREAD

**Issue by Special-G** [2nd-alarm/FiveM#144]
**Describe the bug**
When playing FRD there will be times when you take the stretcher out of the back of the ambulance and when you put it down and pick it back up it will duplicate.  The duplicate is a solid object but you can not interact with it. It also does not go away until a server restart like everything else.

**To Reproduce**
1. Grab an ambulance
2. grab the stretcher
3. put it down
4. pick it back up
5. It may duplicate
6. stow the stretcher in your hands
7. then try to pick up the duplicate. 

**Expected behavior**
This seems like a standard bug and the expectation is that it would not duplicate. 

**Screenshots**
I have added this screenshot for the purpose of showing you that you can not interact with the duplicate stretcher. 
![Screenshot (55)](https://user-images.githubusercontent.com/95453816/160252162-b8376ba4-7d1b-4af2-96dc-10af48c9b2a5.png)

**Additional context**
So I know this may be a little problem but I still think it is worth investigating and here is why. If you think about the screenshot it may not be a big deal because it is in an open area and it is easily bypassed and not in the way. However, I did have this happen to me 2 other times. one in the ambulance bay at pillbox which is an issue because it is a solid object and it makes it hard to move around in that space or to even get the ambulance in. the second place was in the sandy shores hospital in the room with the beds. again making it hard to move around in that room.

**Comment by Mumbleb** [comment]
We are unable to fix duplicating issue. It has been reported to script author multiple times.
