### ISSUE TITLE
[BUG] Weird race track texture at Sandy shores fire station. 

### ISSUE THREAD

**Issue by Special-G** [2nd-alarm/FiveM#145]
**Describe the bug**
I was playing FRD yesterday in sandy shores and I noticed this weird race track type texture coming through the ground. It comes and goes and not all of it shows  sometimes. 

**Expected behavior**
I am unclear if this is supposed to be there as lines to guide the apparatus but if so they disappear sometimes and reappear. they seem a little broken. Not a huge issue just felt in necessary to put in a bug report for it. 

**Screenshots**
![Screenshot (54)](https://user-images.githubusercontent.com/95453816/160252401-be0e03b5-82e8-43b3-8da6-b2370b030775.png)

**Comment by Mumbleb** [comment]
Part of the Fire Station model
