### ISSUE TITLE
[BUG] train bug. 

### ISSUE THREAD

**Issue by Special-G** [2nd-alarm/FiveM#146]
**Describe the bug**
There is a bug in the sandy area and possibly all over the map where the train will got through an area and appear to either duplicate some of the cars or disconnect. I am not sure. The problem this causes is that they are solid objects to the AI so it causes a traffic backup and even a multi vehicle accident that makes the area unusable until the de spawn. I understand that you can just leave the area and they may de spawn but it is still a pain because lots of people like using the county to RP in and with the train bugging out it makes one of the roads unusable. 

There is also another bug where the train gates in the city will activate at the wrong time or not go up when the train is finished going through. I did not get a screen shot of this bug but have seen it happen a couple times. 

**To Reproduce**
1. Go to sandy shores at the intersection of panorama drive and Joshua road. 
2. Wait for the train to come through
3. notice that some of the train cars stay behind 
4. watch AI be unable to pass. 
5. See the traffic issues. 

**Expected behavior**
The expectation form this bug is that the train would not do this and cause this issue. 

**Screenshots**
![Screenshot (56)](https://user-images.githubusercontent.com/95453816/160252576-721b3f12-dd5e-430b-b289-296fa133ecf7.png)

**Additional context**
this may bot be a top priority to fix and I understand that. I think I remember a time when we didnt have stains in the server. Maybe it makes sense to deactivate the trains until a fix can be looked into.

**Comment by Mumbleb** [comment]
Script Removed Pending Further Investigation on DEV Server
