### ISSUE TITLE
[BUG] EOD robot does not work as expected

### ISSUE THREAD

**Issue by acco4321** [2nd-alarm/FiveM#147]
**Describe the bug**
You cannot enter the camera on the EOD robot, nor can you reverse - you have to turn and reverse. 

**To Reproduce**
1. Type `/eod`
2. Try to enter the camera using Enter
3. Observe that you cannot enter
4. Try to reverse using down on the arrow keys

**Expected behavior**
The camera is entered and the robot can reverse without turning.

**Additional context**
keys according to [docs](https://docs.londonstudios.net/index.php/document/eod-how-to-use/)

**Comment by Mumbleb** [comment]
Asset Updated
