### ISSUE TITLE
Vehicles for Civilians 

### ISSUE THREAD

**Issue by hooverguy87784** [2nd-alarm/FiveM#148]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Adding more vehicles for civs to use/buy, AKA Semi-truck, planes, heli, and more. If we want a vehicle we need to steal one or rob a NPC and if a cop sees it we can get arrested, We would like to buy more vehicles to use.
**Describe alternatives you've considered**
Add a spawn menu for vehicles for RP
**Additional context**
N/A
**Links**
Link anything that may help us
N/A

**Comment by Jamie-D-T** [comment]
Already on trello.
