### ISSUE TITLE
Better AI Script

### ISSUE THREAD

**Issue by Special-G** [2nd-alarm/FiveM#149]
**Is your feature request related to a problem? Please describe.**
It is kind of a problem. Anyone who has played as Civ or PD/FD knows that the AI population drives like animals. They cut out in front of you, don't yield to you, and cause a mess. This is base GTA. But, many developers have made numerous scripts that will aid the AI in making better driving decisions. 

**Describe the solution you'd like**
There are many scripts out there that can be plugged into our server. I may not have found the right one or a compatible one but I leave this link as a option and a guide for what I mean. All I am looking for is for the AI to drive and react better than they are right now. I think many scripts have potential to make everyone's driving experience better on all sides. I think this is an important one because the AI in this game are very unforgiving and it is a beautiful thing that there are developers in this world willing to help us out with this. 

**Describe alternatives you've considered**
I have considered the fact that some of the issue may be our driving as players. I understand this 100%. But I do place some of the blame on the AI. I think the AI, with the tools available to us, could be better. With better AI we can then work on players driving because they will have no leg to stand on. 

**Additional context**
I Know the dev team is hard at work. I do not envy you for the work you have to do. This is simply a recommendation on things that I think could make our experiences as players better. Thank you for all that you do for the server. 

**Links**
(https://forum.cfx.re/t/release-real-ai-traffic-1-0/80968)

**Comment by Jamie-D-T** [comment]
Well unfortunately we already use that script as well as tried alternatives but AI just be AI, unfortunately, I fully understand they drive like pigs you just got to avoid them it is mostly due to their mapping in GTA that causes them to pull out in front of you.
