### ISSUE TITLE
[BUG] Phone stuck on hand

### ISSUE THREAD

**Issue by Special-G** [2nd-alarm/FiveM#150]
**Describe the bug**
When you get in game and use your phone, your phone gets stuck to your hand the rest of the time your playing. 

**To Reproduce**
1. get in the server
2. pull out your phone
3. look at anything on your phone
4. close your phone
5. your phone should be stuck to your hand

**Expected behavior**
when you close your phone it shouldnt be stuck to your hand.

**Screenshots**

![Screenshot (76)](https://user-images.githubusercontent.com/95453816/165871202-ec93b459-c990-4d53-943c-537bc0c5943b.png)

**Comment by Mumbleb** [comment]
Unable to reproduce bug

**Comment by Jamie-D-T** [comment]
Relogging fixes it happens intermittently nothing that can be done it's just gta animations not deleting object

**Comment by Special-G** [comment]
If this is the case then I will never be able to use my phone without relogging. It happens the first time I use my phone.

**Comment by Jamie-D-T** [comment]
You will need to reinstall FiveM or your entire game then
