### ISSUE TITLE
New Tow Truck. 

### ISSUE THREAD

**Issue by Special-G** [2nd-alarm/FiveM#153]
**Is your feature request related to a problem? Please describe.**
Not a problem just would be a cool addition to the fleet. 

**Describe the solution you'd like**
This would be a cool addition to the fleet. It also looks like it has a winch which could be helpful at times. there is a video in the link that shows how it works.

**Links**
https://www.gta5-mods.com/vehicles/freightliner-m2-crew-cab-flatbed-add-on-script-beta

**Comment by Jamie-D-T** [comment]
Unuseable due to legal compliance.
