### ISSUE TITLE
Heavy Wrecker for Mechanic Job

### ISSUE THREAD

**Issue by Special-G** [2nd-alarm/FiveM#155]
**Is your feature request related to a problem? Please describe.**
Not a problem, But would be helpful for some situations I found myself in today. I was playing and a call came in for a tow of a armored money truck. Even with the 450 this was a struggle. It was tough to tow and I could have used something bigger. I also got a call to tow a bus that was blocking traffic. This was not towable by any of the vehicles. 

**Describe the solution you'd like**
The link I have attached is for a heavy wrecker. This will help greatly when the situation presents itself that we need something like this. This will allow us to tow vehicles of all sizes and it will allow for better role play in my opinion. I would love to see this added to the tow arsenal. 

**Describe alternatives you've considered**
It doesn't have to be this specific model. if there is another model that would better suit the server then of course use that one. However I do think we need this in the server. Granted this was the first call I have gotten for something like this but it will be helpful for the future.

**Links**
https://www.gta5-mods.com/vehicles/non-els-fivem-ready-kenworth-t440-heavy-wrecker

**Comment by Jamie-D-T** [comment]
This is un-useable it is not possible to use it without compliance with the law.
