### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YaDad** [2nd-alarm/FiveM#26]
A miner can only carry 7 rocks at a time

Become a miner
Go to get some rocks
Realise you can only carry 7/24 

You should be able to carry 24 not 7 rocks

![image](https://user-images.githubusercontent.com/83597225/117539693-aedc5d80-b003-11eb-8df8-b84aac597319.png)

**Comment by Jamie-D-T** [comment]
This is a economy balancing system this is correct.
Thank you for your bug report
