### ISSUE TITLE
Character is unable to exit vehical

### ISSUE THREAD

**Issue by YaDad** [2nd-alarm/FiveM#27]
**Describe the bug**

**To Reproduce**
Steal a mini van.
Drive from the hospital to the weed farm.
Realise you cant leave the vehicle.

**Expected behaviour**
To be able to exit the vehicle by pressing F.

**Comment by YaDad** [comment]
NVM I had the seatbelt on however there is a bit of a problem with the vehicles burning fuel really quick.

**Comment by Jamie-D-T** [comment]
Hello there sorry for the misunderstanding. Please create a new issue regarding fuel usage.
