### ISSUE TITLE
Players not showing up on the player list.

### ISSUE THREAD

**Issue by YaDad** [2nd-alarm/FiveM#28]
**Describe the bug**
Players are not showing up on the player list.

**To Reproduce**
Press the arrow when there is more then 3 people in game.

**Expected behavior**
You see who is in game.

**Comment by ZackDallaire112** [comment]
Please note that this is on the back burner

**Comment by Jamie-D-T** [comment]
This seems to be fixed feel free to raise the issue again if it reoccures
