### ISSUE TITLE
Officers not being able to use the vehicle shop.

### ISSUE THREAD

**Issue by YaDad** [2nd-alarm/FiveM#30]
**Describe the bug**
Officers aren't able to use the vehicle shop at the police station.

**To Reproduce**
Steps to reproduce the behaviour:
Go the the station as a lower ranking officer (I was a cadet).
Attempt to open the police vehicle shop.
Read the error message.

**Expected behaviour**
The vehicle shop opens.

**Additional context**
I know that you 2 already know but here is the report.

**Comment by ZackDallaire112** [comment]
This has now been fixed
