### ISSUE TITLE
Job Center - Job Names

### ISSUE THREAD

**Issue by thefireman504** [2nd-alarm/FiveM#32]
![image](https://user-images.githubusercontent.com/62909235/117829546-7b364900-b238-11eb-9aa1-b601766528f9.png)

**Comment by thefireman504** [comment]
![image](https://user-images.githubusercontent.com/62909235/117845705-69f43900-b246-11eb-8052-8715d1da5329.png)

**Comment by Jamie-D-T** [comment]
![image](https://user-images.githubusercontent.com/63130054/117995783-759f3880-b2f6-11eb-98dc-d9887cabbc25.png)
Needs to be opened in a new issue with some extra description please. 
Thank you

**Comment by ZackDallaire112** [comment]
@thefireman504  Please note that this is 2 different issues in the same ticket please make another ticket for the other issue

**Comment by Jamie-D-T** [comment]
Issues are fixed please in-future keep it to  a single issue per post
Thank you
