### ISSUE TITLE
The game stole my petrol.

### ISSUE THREAD

**Issue by YaDad** [2nd-alarm/FiveM#36]
I died, I was revived and I lost a full tank of Petrol from my inventory.
I want my $200 back!

**Comment by Jamie-D-T** [comment]
@YaDad please raise the $200 back issue to A16 thank you. I will be looking into this bug further.
Thank you

**Comment by Jamie-D-T** [comment]
This is not a bug and you must of illegally obtained the jerry can illegally also just as a note jerry cans are $100 A16 will be more than happy to refund it whenever you are both available if you wish to do so.
