### ISSUE TITLE
Dying resets clothing [BUG]

### ISSUE THREAD

**Issue by PoliceTrooper** [2nd-alarm/FiveM#37]
**Describe the bug**
Upon respawning, a character's clothing will revert back to multiplayer default blue pants and white t-shirt.

**To Reproduce**
1. Die
2. Respawn

**Expected behavior**
The character's clothing should not be reset.

**Comment by Jamie-D-T** [comment]
fixed- charcter should keep their skin and clothing and other accessories- may not keep job uniform however that is not going to be fixed due to game limitations
