### ISSUE TITLE
Police bike became uninteractable [BUG]

### ISSUE THREAD

**Issue by PoliceTrooper** [2nd-alarm/FiveM#38]
**Describe the bug**
After releasing a ped from a traffic stop, the police sahpmoto I was driving became uninteractable. I couldn't get back in the vehicle. I could take cover behind it but that's it.

**To Reproduce**
1. Execute a traffic stop with the sahpmoto by pulling a npc driver over.
2. Perform all searches and checks.
3. Release the npc.
4. Can't get back in the vehicle.

**Expected behavior**
The bike can't be deleted by any admin commands.

**Comment by Jamie-D-T** [comment]
1 in a million chance- vehicle got destroyed
