### ISSUE TITLE
Flat bet towing issue

### ISSUE THREAD

**Issue by YaDad** [2nd-alarm/FiveM#41]
When there is a vehicle on the flatbed the vehicle changes shapes if there is an uneven surface.

Become a mechanic.
Get a flatbed.
Put a vehicle on it.
Watch the vehicle flop around as you drive.
The vehicle flops and compress

https://user-images.githubusercontent.com/83597225/118538871-a2b07880-b746-11eb-849c-4f97afc16fbf.mp4

**Comment by Jamie-D-T** [comment]
This bug is a visual thing and is not necessary to fix this will not be fixed
