### ISSUE TITLE
Mechanic job not working[BUG]

### ISSUE THREAD

**Issue by Mongz-PL1** [2nd-alarm/FiveM#45]
**Describe the bug**
While Selecting jobs in FiveM, the Mechanic job is not working, and there its a "Do not use this" job listed that does nothing. Needs to be taken off the list if possible.

**To Reproduce**
1. Go to Job selction
2. Click on the Jobs listed above.

**Expected behavior**
Nothing happens.

**Additional context**
None

**Comment by PoliceTrooper** [comment]
We are aware of the "do not use this" job, it is a patchwork to a more in-depth removal that is planned.

We will look into the Mechanic job not working properly.

**Comment by Jamie-D-T** [comment]
FIXED- it should have been whitelisted and wasn't now is after restart
