### ISSUE TITLE
Additional Police(+Medic) Uniforms

### ISSUE THREAD

**Issue by thefireman504** [2nd-alarm/FiveM#52]
Right now players are limited to a police officer ped, swat ped, and a sheriff ped, but we have state police and unmarked vehicles. I believe we should add the following other peds to the menu. These are already in GTAV files, so no additional downloads are needed. This will allow police officers to match with their vehicles.

(LAPD with Vest since it looks better than the way we have the vest set up now...)
![image](https://user-images.githubusercontent.com/62909235/120079094-107a6f80-c078-11eb-838e-ff1783eefda9.png)

(FIB for undercover/unmarked units. Possibly for higher ranks only...)
![image](https://user-images.githubusercontent.com/62909235/120079167-4fa8c080-c078-11eb-8f0f-3d5103ef1f84.png)

(Highway Patrol for State Police)
![image](https://user-images.githubusercontent.com/62909235/120079220-8b438a80-c078-11eb-9036-fb98c7cd06dc.png)

(This one for the medic job...)
![image](https://user-images.githubusercontent.com/62909235/120079191-6f3fe900-c078-11eb-85ae-7680a8840509.png)

**Comment by ZackDallaire112** [comment]
We will look into this

**Comment by Jamie-D-T** [comment]
added via command /eup
