### ISSUE TITLE
Change of EUP rids officers of their guns [BUG]

### ISSUE THREAD

**Issue by Mongz-PL1** [2nd-alarm/FiveM#55]
**Describe the bug**
When you /eup and change your clothing/uniform, all weapons disappear from your weapon scroll menu.

**To Reproduce**
1. Go to /eup
2. Click on anything
3. Open weapon menu 
4. See there lack of weapons in your menu

**Expected behavior**
Changing EUP/Uniform shouldnt do this.

**Comment by Jamie-D-T** [comment]
Fixed added a newer version off the EUP
