### ISSUE TITLE
Drug picking field icon is missing[BUG]

### ISSUE THREAD

**Issue by SirMagicTurtle** [2nd-alarm/FiveM#59]
**Describe the bug**
For some players the location of the drug field is no longer shown on the map.
**To Reproduce**
Open your map and look in the area to see if you have a marker for the drug field.
**Expected behavior**
I expect there to be a red circle and a symbol in the location of the drug field.
**Screenshots**
![image](https://user-images.githubusercontent.com/83597225/121789804-107a8380-cbd1-11eb-8d5e-6450f539ddb7.png)

**Comment by PoliceTrooper** [comment]
From your screenshot I also can't see the drug processing icon. Please check if you can see the drug dealer and the money launder icon. If you can't, they are probably disabled for civilians who have a job, which is your case as I can see the fueler's icons on your map.

**Comment by Jamie-D-T** [comment]
Fixed

**Comment by SirMagicTurtle** [comment]
I can confirm that the money laundering icon can be seen on the map, I asked someone else to take the scree shot on my behalf but once I get online I will check as an unemployed character.

**Comment by Jamie-D-T** [comment]
The money laundering icon is separate and this issue is closed therefore it doesn't require a  reply
