### ISSUE TITLE
[BUG] Cannabis / marijuana incorrectly counted in inventory

### ISSUE THREAD

**Issue by ThanksBarack** [2nd-alarm/FiveM#62]
**Describe the bug**
Cannabis and marijuana are both incorrectly totally in a player's inventory. 1 cannabis takes up 3 inventory slots and 1 marijuana takes up 2 inventory slots.

**To Reproduce**
1. Take note of your player inventory counts. [Example 100/1000]
2. Obtain 6 cannabis plants.
3. Take note of your player inventory counts. [If you added 6 cannabis your inventory now shows 118/1000 instead of 106/1000]
4. Convert 6 cannabis to marijuana at the weed processing facility.
5. Take note of your player inventory counts. Marijuana is taking up twice as much space as it should.

**Expected behavior**
1 cannabis should take up 1 inventory slot. 1 marijuana should take up 1 inventory slot.

**Screenshots**
N/A

**Comment by Jamie-D-T** [comment]
This is actually intended to be the case however there should be a limit to allow you to only carry 20 cannabis
