### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by blueyblueblue9** [2nd-alarm/FiveM#64]
**Describe the bug**
at 8050 the gaming cafe you can drive through the wall and get your car stuck inside.

**To Reproduce**
1. Get a vehicle 
2. Go to 8050
3. Drive into the wall (the left of the door)
4. Have fun getting out.

**Expected behavior**
You glitch into the building and sometimes under the ground.

**Screenshots**
![FiveM - 2nd Alarm RP 20_07_2021 16_55_08](https://user-images.githubusercontent.com/87574361/126356372-5ddc3cb3-70b2-43f6-904a-c65639b51ffe.png)
![FiveM - 2nd Alarm RP 20_07_2021 16_55_00](https://user-images.githubusercontent.com/87574361/126356386-91b5e7bb-6b3f-4199-b197-f2332f6b218f.png)
![FiveM - 2nd Alarm RP 20_07_2021 16_54_52](https://user-images.githubusercontent.com/87574361/126356391-07af66e1-c3ea-4302-9637-485c85cb3bc0.png)
![FiveM - 2nd Alarm RP 20_07_2021 16_53_00](https://user-images.githubusercontent.com/87574361/126356456-4a2d4876-429e-43b6-bd86-7a123a4b577b.png)
![FiveM - 2nd Alarm RP 20_07_2021 16_52_51](https://user-images.githubusercontent.com/87574361/126356470-82c73fbf-0ebe-40cd-a330-3ec2b5c90473.png)
![unknown](https://user-images.githubusercontent.com/87574361/126356543-b2678685-cd06-493f-9313-6e19d9604944.png)

**Additional context**
if you just place a box in front of the left side of the wall it will stop people from driving through it.

**Comment by Jamie-D-T** [comment]
Well, all I can say is just don't if you lose your car to it. It will not be refunded.
