### ISSUE TITLE
Open All Interiors

### ISSUE THREAD

**Issue by blueyblueblue9** [2nd-alarm/FiveM#65]
**Is your feature request related to a problem? Please describe.**
No, I just think it would be cool to have more interiors

**Describe the solution you'd like**
I would like to be able to walk into some of the buildings for roleplay aspects.

**Describe alternatives you've considered**
I mean its either a mod or using CodeWalker to customize the map and edit it yourself.

**Additional context**
Nothing Else

**Links**
https://www.gta5-mods.com/scripts/open-all-interiors

**Comment by Jamie-D-T** [comment]
Moved to trello
