### ISSUE TITLE
Weazel News Job

### ISSUE THREAD

**Issue by blueyblueblue9** [2nd-alarm/FiveM#66]
**Is your feature request related to a problem? Please describe.**
No I just want some more jobs for like weazel news!

**Describe the solution you'd like**
A job and possibly a camera.

**Describe alternatives you've considered**
THERE IS NO ALTERNATIVES WE NEED WEAZEL NEWS

**Additional context**
WEAZEL NEWS ARE PROS

**Links**
Link anything that may help us

**Comment by Jamie-D-T** [comment]
Moved to trello
