### ISSUE TITLE
Object Spwner for FRD!

### ISSUE THREAD

**Issue by blueyblueblue9** [2nd-alarm/FiveM#67]
**Is your feature request related to a problem? Please describe.**
It's kinda a problem when you're trying to roleplay a scene and you have to call PD to place cones.

**Describe the solution you'd like**
The same menu as PD do for spawning in things.

**Describe alternatives you've considered**
You can remove the police barrier.

**Additional context**
Nah

**Links**
Link anything that may help us

**Comment by Jamie-D-T** [comment]
Yes I will be looking into this hopefully I can find a solution

**Comment by Jamie-D-T** [comment]
added but is buggy going to hopefully patch
