### ISSUE TITLE
Being able to save multiple outfits at once.

### ISSUE THREAD

**Issue by blueyblueblue9** [2nd-alarm/FiveM#68]
**Is your feature request related to a problem? Please describe.**
If I ever want to switch what outfit I'm wearing I need to get rid of the old one just to get a new one.

**Describe the solution you'd like**
A simple way to save outfits so I can have multiple of the same outfit.

**Additional context**
Anything like GTA online's outfits changer would be nice.

**Comment by Jamie-D-T** [comment]
Explain further

**Comment by Jamie-D-T** [comment]
nothing further added going to close
