### ISSUE TITLE
[BUG] Ambulance Actions at Davis Station

### ISSUE THREAD

**Issue by ZackDallaire112** [2nd-alarm/FiveM#70]
**Describe the bug**
Ambulance actions are in the void at Davis station

**Expected behavior**
Supposed to the be in the Bay

**Screenshots**
Unable

**Additional context**

**Comment by Jamie-D-T** [comment]
> **Describe the bug**
> Ambulance actions are in the void at Davis station
> 
> **Expected behavior**
> Supposed to the be in the Bay
> 
> **Screenshots**
> Unable
> 
> **Additional context**

needs an actual explanation

**Comment by ZackDallaire112** [comment]
It was a bug I was trying to fix this, Basically davis station is set up to have an interior
