### ISSUE TITLE
[BUG] Player Console

### ISSUE THREAD

**Issue by ZackDallaire112** [2nd-alarm/FiveM#71]
**Describe the bug**
Instead of pulling up the player list it displays an error on the fivem console

**To Reproduce**
1. Hit 0 
2. Get error on console

**Expected behavior**
Instead of pulling up the player list it now instead puts an error in console

**Screenshots**
![image](https://user-images.githubusercontent.com/83617670/130303243-b7995928-c28f-4418-810d-5071fca6378c.png)

**Additional context**
Nothing

**Comment by Jamie-D-T** [comment]
> **Describe the bug**
> Instead of pulling up the player list it displays an error on the fivem console
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Hit 0
> 2. Get error on console
> 
> **Expected behavior**
> Instead of pulling up the player list it now instead puts an error in console
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/83617670/130303243-b7995928-c28f-4418-810d-5071fca6378c.png)
> 
> **Additional context**
> Nothing

not a bug it is just when you first make a character it won't work
