### ISSUE TITLE
[BUG] when you put 911 it gives an error in console

### ISSUE THREAD

**Issue by ZackDallaire112** [2nd-alarm/FiveM#72]
**Describe the bug**
Instead of sending a 911 call out when you hit g it makes a error in console

**To Reproduce**
1. Die 
2. Hit G
3. Check FiveM Console

**Expected behavior**
A 911 call goes out

**Screenshots**
![image](https://user-images.githubusercontent.com/83617670/130303317-f68f22f5-3246-4a43-bd62-8bae61eae4b3.png)

**Additional context**
Sitting here dead...

**Comment by Jamie-D-T** [comment]
> **Describe the bug**
> Instead of sending a 911 call out when you hit g it makes a error in console
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Die
> 2. Hit G
> 3. Check FiveM Console
> 
> **Expected behavior**
> A 911 call goes out
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/83617670/130303317-f68f22f5-3246-4a43-bd62-8bae61eae4b3.png)
> 
> **Additional context**
> Sitting here dead...

G doesn't generate a 911 call it creates a blip on you
