### ISSUE TITLE
Window tint "default" option does not restore tint to original "no tint" configuration

### ISSUE THREAD

**Issue by jbaese** [2nd-alarm/FiveM#81]
Captured video here of what I experienced trying to remove window tint at the customs shop. It appears the "default" option retains whatever you pulled into the shop with and not the original default tintless option. Limo tint appears to be the only tint that allows any interior light to show outside the vehicle.
https://drive.google.com/file/d/1xZ9UOt4UTqDrbmo7tE0HaGq4Gg8Jz8xF/view?usp=sharing

**Comment by Jamie-D-T** [comment]
Does not fit template and cannot reproduce
