### ISSUE TITLE
Miner outfit not working.

### ISSUE THREAD

**Issue by SirMagicTurtle** [2nd-alarm/FiveM#86]
**Describe the bug**
The Miner job is not allowing some to change outfitsinorder to go in-service as a Miner.

**To Reproduce**

Note: this is not my own personal experience so I can not describe the recreation of this bug. Also note that this bug may not apply to everyone.

**Expected behavior**
Going to the Miner "locker room" should allow you to change to a work outfit, in tuen also allowing you to go inservice and work as a Miner.

**Screenshots**
![Screenshot_20211002-011449_Discord](https://user-images.githubusercontent.com/83597225/135697736-9abf4560-6028-4470-be12-c5fa2efa5135.jpg)

**Additional context**
You may need to contact the origional reporter of the bug.

**Comment by Jamie-D-T** [comment]
Bug reports by proxy are not accepted with the exception of bug reports fully investigated by A01, A16, B01, B17
