### ISSUE TITLE
Adding someone to the police job doesn't fully display the job until relog

### ISSUE THREAD

**Issue by PoliceTrooper** [2nd-alarm/FiveM#9]
After adding a player to the police job, they need to leave and rejoin the server for the job's rank to display. The "police" part shows, but not the rank.

**Comment by Jamie-D-T** [comment]
Issue reoccurred post pre-alpha reset

**Comment by Jamie-D-T** [comment]
This is been investigated and will be patched shortly

**Comment by Jamie-D-T** [comment]
Will not be fixed as it doesn't affect the gaming experience
